sudo: required

language: php

services:
  - docker

before_install:
  - docker build -t quay.io/wunder/fuzzy-alpine-php-fpm .
  - docker run --detach --name fpm quay.io/wunder/fuzzy-alpine-php-fpm

script:
  # this is an ps style ping, that will only run if the service is running
  - docker ps
  